apiVersion: v1
kind: Service
metadata:
  annotations:
    # service.beta.kubernetes.io/do-loadbalancer-certificate-id: ""
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-protocol: https
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
  name: load-balancer
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9898
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9898
  - port: 9999
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    app: podinfo
  sessionAffinity: None
  type: LoadBalancer
